//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoList
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public string UserName { get; set; }
        public int TaskID { get; set; }
    
        public virtual Chore Chore { get; set; }
        public object TaskViewModel { get; internal set; }
    }
}
