//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoList
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Taska2Entities : DbContext
    {
        public Taska2Entities()
            : base("name=Taska2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Chore> Chores { get; set; }
        public virtual DbSet<Record> Records { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public object TaskViewModel { get; internal set; }
    }
}
